language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t uday-singh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true uday-singh/docker-react npm run test
